steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/nlp-lstm-457707/flask-github-visualizer', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/nlp-lstm-457707/flask-github-visualizer']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - 'flask-github-service'
    - '--image=gcr.io/nlp-lstm-457707/flask-github-visualizer'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8080'

logsBucket: "gs://sprm5_lstmbucket"
